openapi: 3.0.3
servers:
  - url: "http://localhost:3000/v1"
info:
  title: WASAText
  description: |-
   Connect with your friends effortlessly using WASAText!
   Send and receive messages, whether one-on-one or in groups,   all from
   the convenience of your PC. Enjoy seamless conversations with text or
   GIFs and easily stay in touch through your private chats or group
   discussions.
  version: 1.0.0
security:
  - BearerAuth: []


tags:
  - name: login
    description: ops related to login or account creation
  - name: chatlvl
    description: ops on one chat/group
  - name: msglvl
    description: ops on a single message
  - name: pfl
    description: ops on one's or someone else's profile
  - name: user
    description: ops on a user
  - name: reac
    description: op on a reaction
  - name: General
    description: app updates, generic info

paths:
  /status:
    parameters:
      - $ref: "#/components/parameters/XAppBuild"
      - $ref: "#/components/parameters/XAppVersion"
      - $ref: "#/components/parameters/XAppLanguage"
    get:
      tags: ["General"]
      operationId: getStatusMessage
      summary: Get status message for the user about issues / updates
      description: |-
        The response contains a status message meant for the user. It might
        contains information about current technical issues, update messages
        or general information.
      responses:
        "200":
          description: Status message available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusInfo"
              example:
                status: info
                title: all right
                message: no issues found
        "400": { $ref: "#/components/responses/BadRequest" }
        "500": { $ref: "#/components/responses/InternalServerError" }
  /session: 
    post:
      tags: ["login"]
      summary: logs in the user
      description: |-
        creates a user if it doesn't exist, and returns identifier
        if it exists, just returns the user identifier
      operationId: doLogin
      requestBody:
        description: user details
        required: true
        content:
          application/json:
            schema:
              type: object
              description: request contains the userId of the requestor
              required:
                - name
              properties:
                name:
                  type: string
                  description: unique alphanum username
                  example: "Maria02"
                  minLength: 3
                  maxLength: 16
                  pattern: '^[a-zA-Z0-9]+$'
      responses:
        '201':
          description: user login successful
          content:
            application/json:
              example:
                identifier: d66ce88d-ba24-41bf-b53a-20afdf9e9088
              schema:
                type: object
                description: bearer authentication identifier
                properties:
                  identifier:
                    type: string
                    format: uuid
                    description: identifier of auth user
                    pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
                    minLength: 36
                    maxLength: 36
        '400': {$ref: "#/components/responses/BadRequest"}
        '401': {$ref: "#/components/responses/Unauthorized"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /users:
    get:
      operationId: searchUsers
      summary: finds users based on search key
      description: finds all users that contain the search key (case-sensitive), returns a list of users
      tags: ["user"]
      parameters:
        - in: query
          name: searchkey
          required: false
          description: part or whole username to look for
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]+$'
            minLength: 1
            maxLength: 16

      responses:
        '200':
          description: user list found
          content:
            application/json:
              example:
                users: [] #idk how to put in username and userId here
              schema:
                type: object
                description: list of users that match the search key
                required:
                  - users
                properties:
                  users:
                    type: array
                    description: users matching search key
                    minItems: 0
                    maxItems: 1000000 # check back what limit was set for project
                    items:
                      $ref: "#/components/schemas/User"
        '204': { $ref: "#/components/responses/NoContent"}
        "400": { $ref: "#/components/responses/BadRequest" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /users/{userId}:
    parameters:
      - $ref: "#/components/parameters/userId"
    get:
      operationId: getUserProfile
      summary: gets user info, including oneself
      tags: ["user"]
      description: fetches username and profile picture, returns bad req if user is not found
      responses:
        '200':
          description: 'user info'
          content:
            application/json:
              example:
                username: abc2
                userId: d66ce88d-ba24-41bf-b53a-20afdf9e9088
              schema:
                $ref: "#/components/schemas/User"
        "400": { $ref: "#/components/responses/BadRequest" }
        "404": { $ref: "#/components/responses/NotFound"}
        "500": { $ref: "#/components/responses/InternalServerError" }

  /profile/username:
    put:
      operationId: setMyUserName
      tags: ["user", "pfl"]
      summary: change username
      description: |-
        Modifies current username to another unique alphanum string
        chosen by the user
      requestBody:
        required: true
        description: new username for auth user
        content:
            application/json:
              example:
                targetusername: maria5
              schema:
                type: object
                description: req containing new username to apply to auth user
                required:
                  - targetusername
                properties:
                  targetusername:
                    type: string
                    description: new (unique) username
                    example: "Maria03"
                    minLength: 3
                    maxLength: 16
                    pattern: '^[a-zA-Z0-9]+$'
      responses:
        '200': 
          description: username changed succefssfully
          content: {}
        "400": { $ref: "#/components/responses/BadRequest" }
        "409": { $ref: "#/components/responses/Conflict" }
        "500": { $ref: "#/components/responses/InternalServerError" }


  /profile/photo:
    put:
      operationId: setMyPhoto
      tags: ["pfl"]
      summary: changes one's profile picture
      description: |-
        Modifies current profile photo to another. Optional feature: when
        user deletes their own photo/chooses not to have one, use a black
        or white picture
      requestBody:
        description: jpg img to use as new pfp picture
        required: true
        content:
            image/jpeg:
              schema:
                type: string
                description: the jpg image file of the new profile picture
                format: binary
                minLength: 1
                maxLength: 10485760
      responses:
        '200': 
          description: group photo changed successfully
          content: {}
        "400": { $ref: "#/components/responses/BadRequest" }
        "500": { $ref: "#/components/responses/InternalServerError" }

  /chats:
    get:
      operationId: getMyConversations
      tags: ["chatlvl"]
      summary: gets one's conversations in a list
      description: |-
        returns all chats in reverse chronological order, along with the
        latest message preview and timestamp
      responses:
        '200':
          description: list of conversations
          content:
            application/json:
              example:
                chats: []
              schema:
                type: object
                description: list of chats belonging to user
                required:
                  - chats
                properties:
                  chats:
                    type: array
                    description: chats belonging to user
                    minItems: 0
                    maxItems: 200
                    # should add a check in backend's makechat and makegroup
                    items:
                      $ref: "#/components/schemas/Chat"
        # '204': {$ref: "#/components/responses/NoContent"}
        '500': {$ref: "#/components/responses/InternalServerError"}

    post: 
      operationId: makeChatGroup
      tags: ["chatlvl"]
      summary: create a new chat or group
      description: |- 
        returns the chat if successful. (check that, if chat is private and it already
        exists, it doesn't do anything but returns that chat)
      requestBody:
        required: true
        description: members of the private chat to-be
        content:
          application/json:
            example:
              members:
                - d66ce88d-ba24-41bf-b53a-20afdf9e9088
                - d66ce88d-ba24-41bf-b53a-20afdf9e9089
              groupname: Homechat
            schema:
              type: object
              description: list of members (min 2, max 100) to put in the chat/group
              required:
                - members
              properties:
                members:
                  type: array
                  description: userIds of the chat members
                  minItems: 2
                  maxItems: 100
                  items:
                    type: string
                    format: uuid
                    minLength: 36
                    maxLength: 36
                    description: userId of a chat/group member
                    pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
                groupname:
                  type: string
                  description: name of the group if chat is a group
                  pattern: '^[a-zA-Z0-9]+$'
                  minLength: 1
                  maxLength: 40
      responses:
        '201':
          description: chat/group created successfully
          content:
            application/json:
              example:
                chatId: d66ce88d-ba24-41bf-b53a-20afdf9e9088
                chatName: Homechat
                groupOrChat: group
                members:
                  - d66ce88d-ba24-41bf-b53a-20afdf9e9070
                  - d66ce88d-ba24-41bf-b53a-20afdf9e9071
                creationDate: "2026-01-01T12:00:00Z"
              schema:
                $ref: "#/components/schemas/Chat"
          links: 
            getConversation:
              operationId: getConversation
              description: the chat output can be used to look for that chat resource
              parameters:
                chatId: $response.body#/chatId
        '400': {$ref: "#/components/responses/BadRequest"}
        '409': {$ref: "#/components/responses/Conflict"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}:
    parameters:
      - $ref: "#/components/parameters/chatId"
    delete:
      operationId: leaveGroup
      tags: ["chatlvl"]
      summary: leave a group or chat
      description: |-
        Can work for both chats and groups because the case 
        where you leave a group and it remains with one member
        creates no conflict with self private chats, as groups are NOT
        unique
      responses:
        '204': {$ref: "#/components/responses/NoContent"}
        '400': {$ref: "#/components/responses/BadRequest"}
        '403': {$ref: "#/components/responses/Forbidden"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}/members:
    parameters:
      - $ref: "#/components/parameters/chatId"
    post:
      operationId: addToGroup
      summary: add a member to a group
      description: |-
        adds one or multiple users to an existing group 
      tags: ["chatlvl"]
      requestBody:
        required: true
        description: userId(s) of the user(s) to add to the group
        content:
          application/json:
            example: 
              targetuserIds:
                - d66ce88d-ba24-41bf-b53a-20afdf9e9088
                - d66ce88d-ba24-41bf-b53a-20afdf9e9089
            schema:
              type: object
              description: userIds to add to groupID
              required:
                - targetuserIds
              properties:
                targetuserIds:
                  type: array
                  description: userIds of the users to be added
                  minItems: 1
                  maxItems: 100
                  items:
                    type: string
                    description: userId of the user to be added
                    minLength: 36
                    maxLength: 36
                    pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
                  #removed groupID to clear up the routing architecture
      responses:
        '200':
          description: new member(s) added
          content:
            application/json:
              example:
                chatId: d66ce88d-ba24-41bf-b53a-20afdf9e9088
                chatName: Homechat
                groupOrChat: group
                members:
                  - d66ce88d-ba24-41bf-b53a-20afdf9e9070
                creationDate: "2026-01-01T12:00:00Z"
              schema:
                $ref: "#/components/schemas/Chat"
        '400': {$ref: "#/components/responses/BadRequest"} #or user already iin group
        '403': {$ref: "#/components/responses/Forbidden"} 
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}/photo:
    parameters:
      - $ref: "#/components/parameters/chatId"
    put: 
      operationId: setGroupPhoto
      summary: modify current group photo
      description: deletes old group photo from db and mem and adds to db the new one
      tags: ["chatlvl"]
      requestBody:
        required: true
        description: new image to set as group photo
        content:
          image/jpeg:
            schema:
              type: string
              format: binary
              description: jpg image file of the new group picture
              minLength: 1
              maxLength: 10485760
      responses:
        '200':
          description: group photo changed successfully
          content: {}
        '400': {$ref: "#/components/responses/BadRequest"}
        '403': {$ref: "#/components/responses/Forbidden"}
        '404': {$ref: "#/components/responses/NotFound"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}/groupname:
    parameters:
      - $ref: "#/components/parameters/chatId"
    put: 
      operationId: setGroupName
      summary: modifies current group name
      description: changes db entry on group name
      tags: ["chatlvl"]
      requestBody:
        required: true
        description: new (alphanum) group name
        content:
          application/json:
            schema:
              type: object
              description: the new name for the groupname
              required:
                - groupname
              properties:
                groupname:
                  type: string
                  description: new name for groupname
                  pattern: '^[a-zA-Z0-9]+$'
                  minLength: 1
                  maxLength: 40
      responses:
        '200':
          description: group name change successful
          content: {}
        '400': {$ref: "#/components/responses/BadRequest"}
        '403': {$ref: "#/components/responses/Forbidden"}
        '404': {$ref: "#/components/responses/NotFound"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}/messages:
    parameters: 
      - $ref: "#/components/parameters/chatId"
    get:
      operationId: getConversation
      tags: ["chatlvl"]
      summary: returns a single group or chat's msg list
      description: returns all msgs in reverse chronological order (older messages are at the top)
      responses:
        '200':
          description: convo retrieved
          content:
            application/json:
              example:
                messages: []
              schema:
                type: object
                description: list of messages in chat
                required:
                  - messages
                properties:
                  messages:
                    type: array
                    description: messages in the chat
                    minItems: 0
                    maxItems: 1000000 # might need more?
                    items:
                      $ref: "#/components/schemas/Message"
        '400': {$ref: "#/components/responses/BadRequest"}
        '500': {$ref: "#/components/responses/InternalServerError"}

    post:
      operationId: sendMessage
      tags: ["msglvl"]
      summary: sned a message containing text, image or both
      description: |-
        creates a message to store both in a db entry and in memory, both
        text and image
      requestBody:
        required: true
        description: msg containing txt, img or both
        content:
          multipart/form-data:
            schema:
              oneOf:
                - $ref: "#/components/schemas/SendMessageReq"
                - $ref: "#/components/schemas/SendPhotoMessageReq"
                - $ref: "#/components/schemas/SendTxtPhotoMessageReq"
      responses:
        '201':
          description: message sent
          content:
            application/json:
              example: 
                messageId: d66ce88d-ba24-41bf-b53a-20afdf9e9088
                senderId: d66ce88d-ba24-41bf-b53a-20afdf9e9090
                status: sent
                timestamp: "2026-01-01T12:00:00Z"
                content: "haiii"
                reactions: []
              schema:
                $ref: "#/components/schemas/Message"

        '400': {$ref: "#/components/responses/BadRequest"}
        '403': {$ref: "#/components/responses/Forbidden"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}/messages/{messageId}:
    parameters:
      - $ref: "#/components/parameters/chatId"
      - $ref: "#/components/parameters/messageId"
    delete:
      operationId: deleteMessage
      summary: deletes a message for every member of a chat or group
      description: |-
        deletes db entry, image and message text from memory
      tags: ["msglvl"]
      responses:
        '204': {$ref: "#/components/responses/NoContent"}
        '400': {$ref: "#/components/responses/BadRequest"}
        '403': {$ref: "#/components/responses/Forbidden"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}/messages/{messageId}/forward:
    parameters:
      - $ref: "#/components/parameters/chatId"
      - $ref: "#/components/parameters/messageId"
    post:
      operationId: forwardMessage
      summary: message forward
      tags: ["msglvl"]
      description: forwards messageId to destinationchatId. allowed across all chats and groups
      requestBody:
        required: true
        description: request containing destinationchatId
        content:
          application/json:
            schema:
              type: object
              description: req containing the id of the chat to forward to
              required:
                - destinationchatId
              properties:
                destinationchatId:
                  type: string
                  format: uuid
                  minLength: 36
                  maxLength: 36
                  pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
                  description: ID of the chat the msg is being fwd to
      responses:
        '201':
          description: message forwarded
          content:
            application/json:
              example:
                messageId: d66ce88d-ba24-41bf-b53a-20afdf9e9088
                senderId: d66ce88d-ba24-41bf-b53a-20afdf9e9080
                status: sent
                timestamp: "2026-01-01T12:00:00Z"
                content: "forwarded msg content"
                reactions: []
              schema:
                $ref: "#/components/schemas/Message"
        '400': {$ref: "#/components/responses/BadRequest"} #target userId does not exist?
        '403': {$ref: "#/components/responses/Forbidden"}
        '500': {$ref: "#/components/responses/InternalServerError"}

  /chats/{chatId}/messages/{messageId}/reactions:
    parameters:
      - $ref: "#/components/parameters/chatId"
      - $ref: "#/components/parameters/messageId"
    post:
      operationId: commentMessage
      summary: adds a reaction to a message
      description: one reaction per user
      tags: ["reac"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Reaction"
      responses:
        '201':
          description: reaction added
          content:
            application/json:
              example:
                reactionId: d66ce88d-ba24-41bf-b53a-20afdf9e9088
                userId: d66ce88d-ba24-41bf-b53a-20afdf9e9080
                emoji: "👍"
              schema:
                $ref: "#/components/schemas/Reaction"
          links:
            uncommentMessage:
              operationId: uncommentMessage
              description: the output can be used to check whether user has already reacted
              parameters: 
                reactionId: $response.body#/reactionId
                messageId: $request.path.messageId
                chatId: $request.path.chatId
        '400': {$ref: "#/components/responses/BadRequest"}
        #DELETED 409!
        '403': {$ref: "#/components/responses/Forbidden"}
        '500': {$ref: "#/components/responses/InternalServerError"}


  /chats/{chatId}/messages/{messageId}/reactions/{reactionId}:
    parameters:
      - $ref: "#/components/parameters/chatId"
      - $ref: "#/components/parameters/messageId"
      - $ref: "#/components/parameters/reactionId"
    delete:
      operationId: uncommentMessage
      summary: removes own reaction to a message
      description: idempotent, removing again does nothing
      tags: ["reac"]
      responses:
        '204': {$ref: "#/components/responses/NoContent"}
        '400': {$ref: "#/components/responses/BadRequest"}
        '403': {$ref: "#/components/responses/Forbidden"}
        '500': {$ref: "#/components/responses/InternalServerError"}




components:
  schemas:
    SendMessageReq:
      type: object
      description: the request body for sending or forwarding a message
      required:
        - content
      properties:
        content:
          type: string
          pattern: '^[\s\S]+$'
          minLength: 1
          maxLength: 20000
          description: text contents of msg
        replyTo: 
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: optional ID of an id a user may be replying to
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'

    SendPhotoMessageReq:
      type: object
      description: the request body for sending or forwarding a picture message
      required:
        - photo
      properties:
        photo:
          type: string
          format: binary
          minLength: 1
          maxLength: 10485760 
          description:  jpg image file to be sent
        replyTo:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
          description: (optional) msgID of the msg being replied to
    SendTxtPhotoMessageReq:
      type: object
      description: req body for messages with both text and img
      required:
        - content
        - photo
      properties:
        content:
          type: string
          pattern: '^[\s\S]+$'
          minLength: 1
          maxLength: 20000
          description: text caption for the message
        photo:
          type: string
          description: image to be sent
          format: binary
          minLength: 1
          maxLength: 10485760

          #--------------------------------------------------------------

    Chat:
      type: object
      description: the set of attributes making up a chat
      required:
        - chatId
        - groupOrChat
        - chatName
        - members
        - creationDate
      properties:
        chatId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: unique identifier of the chat
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        chatName:
          type: string
          description: if private, not needed (frontend will display name of the other user), otherwise an alphanum representing the name of a group
          minLength: 1
          maxLength: 50
          pattern: '^[a-zA-Z0-9]+$'
        members:
          type: array
          description: userIds of the members belonging to a chat or group
          minItems: 1
          maxItems: 100
          items:
            type: string
            format: uuid
            minLength: 36
            maxLength: 36
            description: userId of a member
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        creationDate:
          type: string
          format: date-time
          minLength: 1
          maxLength: 64
          description: date and time of chat creation
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'
        groupOrChat:
          type: string
          description: whether the given chat is private or group
          enum:
            - chat
            - group
          minLength: 4
          maxLength: 5
          pattern: '^(chat|group)$'
        photouri:
          type: string
          format: url
          minLength: 1
          maxLength: 2048
          description: pfp url for a group, absent if private chat (frontend will show other user's pfp)
          pattern: '^https?://.+$'
        mostrecentmsg:
          $ref: "#/components/schemas/MessagePreview"

    User:
      title: user
      description: |-
        a generic user: can refer to oneself, or to other persons
        perusing the app.
      type: object
      required:
        - username
        - userId
      properties:
        photouri:
          description: url of the profile picture of the user
          type: string
          format: url
          minLength: 1
          maxLength: 2048
          pattern: '^https?://.+$'
        username:
          description: unique username, alphanumeric
          type: string
          pattern: '^[a-zA-Z0-9]+$'
          example: "Maria02"
          minLength: 3
          maxLength: 16
          readOnly: true
        userId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: unique id of a user
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'

    Message:
      title: message
      description: a single message from a user at a specific date-time (to a specific chat)
      type: object
      required:
        - messageId
        - senderId
        - status
        - timestamp
      properties:
        messageId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: unique id of the message
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        senderId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: userId of the message sender
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        status:
          type: string
          description: delivery status of the message
          enum:
            - sent
            - delivered
            - read
          minLength: 4
          maxLength: 9
          pattern: '^(sent|delivered|read)$'
        timestamp:
          type: string
          format: date-time
          minLength: 1
          maxLength: 64
          description: date and time when the message was sent
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'
        reactions:
          type: array
          description: reactions added to the message
          minItems: 0
          maxItems: 100
          items: {$ref: "#/components/schemas/Reaction"}
        replyTo:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: ID of the message being replied to
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        fwdFrom: 
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: ID of the original message or sender associated with the forwarded message
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
      oneOf:
        - type: object
          description: txt only message option
          required:
            - content
          properties:
            content:
              type: string
              description: text contents of msg
              minLength: 1
              maxLength: 20000
              pattern: '^[\s\S]+$'
        - type: object
          description: img only msg option
          required:
            - photouri
          properties:
            photouri:
              type: string
              format: url
              minLength: 1
              maxLength: 2048
              description: url of msg img
              pattern: '^https?://.+$'
        - type: object
          description: text AND img option
          required:
            - content
            - photouri
          properties:
            content:
              type: string
              description: text contents of msg
              minLength: 1
              maxLength: 1000 #similar model to main texting apps
              pattern: '^[\s\S]+$'
            photouri:
              type: string
              format: url
              minLength: 1
              maxLength: 2048
              description: url of msg img
              pattern: '^https?://.+$'
    
    MessagePreview:
      title: message preview
      description: preview of the most recent msg in a conversation
      type: object
      required:
        - messageId
        - timestamp
        - contentType
        #can't use content and photo
      properties:
        senderId:
          type: string
          format: uuid
          description: userId of the msg sender
          minLength: 36
          maxLength: 36
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        content:
          description: text of msg, absent when msg is img-only
          type: string
          pattern: '^[\s\S]+$'
          minLength: 1
          maxLength: 20000 #maybe I should cut off the msg? or is it a frontend task?
        contentType:
          type: string
          description: whether msg is text, photo or both
          enum:
            - text
            - photo
            - text_photo
          minLength: 4
          maxLength: 10
          pattern: '^(text|photo|text_photo)$'
        timestamp:
          type: string
          format: date-time
          minLength: 1
          maxLength: 64
          description: time and date of sending the msg
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T'
        messageId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: unique id of the msg
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
    Reaction:
      description: |-
        an emoticon added by a user (including oneself) at the foot of a message
        feature: one reaction per user per message
      type: object
      required:
        - emoji
        - userId
        - reactionId
      properties:
        userId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: ID of the user owning the reaction
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
        emoji:
          type: string
          description: emoji used for the reaction
          minLength: 1
          maxLength: 8
          pattern: '^.{1,8}$'
        reactionId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: ID of the reaction
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
    StatusInfo:
      title: Status Info
      type: object
      description: state of the app, regarding updates and issues
      required:
        - status
        - title
        - message
      properties:
        status:
          type: string
          description: severity of app status
          enum:
            - info
            - warning
            - critical
          minLength: 4
          maxLength: 8
          pattern: '^(info|warning|critical)$'
        title:
          type: string
          description: short title of the status msg
          minLength: 1
          maxLength: 100
          pattern: '^.+$'
        message:
          type: string
          description: more detailed status msg
          minLength: 1
          maxLength: 1000
          pattern: '^.+$'
        url:
          type: string
          format: url
          description: optional url for more information
          minLength: 1
          maxLength: 2048
          pattern: '^https?://.+$'

  responses:
    Unauthorized: #401
      description: access token missing or expired
      content:
        application/json:
          schema:
            type: object
            description: error info
            required:
              - message
            properties:
              message:
                type: string
                description: 401 Unauthorised + explanation
                minLength: 1
                maxLength: 500
                pattern: '^.+$'
    BadRequest: #400
      description: request not compliant with app behaviour/needs
      content:
        application/json:
          schema:
            type: object
            description: error info
            required:
              - message
            properties:
              message:
                type: string
                description: bad req
                minLength: 1
                maxLength: 500
                pattern: '^.+$'

    Forbidden:
      description: no auth for user to commit this action
      content:
        application/json:
          schema:
            type: object
            description: more info for the forbidden error
            required:
              - message
            properties:
              message:
                type: string
                pattern: '^.+$'
                minLength: 1
                maxLength: 500
                description: error message explanation

    NoContent: #204
      description: success, no content

    NotFound: #404
      description: requested resource not found
      content:
        application/json:
          schema:
            type: object
            description: error information for 404
            required:
              - message
            properties:
              message:
                type: string
                pattern: '^.+$'
                minLength: 1
                maxLength: 500
                description: explanation of what resource was not found


    Conflict: #409
      description: resource with same key already exists
      content:
        application/json:
          schema:
            type: object
            description: more info on error 409
            required:
              - message
            properties:
              message:
                type: string
                description: explanation on which sources are in conflict
                minLength: 1
                maxLength: 500
                pattern: '^.+$'
    
    InternalServerError: #500
      description: server had an internal error. More info in server logs
      content:
        application/json:
          schema:
            type: object
            description: error info for 500
            required:
              - message
            properties:
              message:
                type: string
                description: more info on the cause of the 500
                minLength: 1
                maxLength: 500
                pattern: '^.+$'

  securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer

  parameters:
    chatId:
      name: chatId
      in: path
      required: true
      description: unique identifier of the chat or group
      schema:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'

    messageId:
      name: messageId
      in: path
      required: true
      description: unique identifier of a message
      schema:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'

    userId:
      name: userId
      in: path
      required: true
      description: unique identifier of a user
      schema:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'

    reactionId:
      name: reactionId
      in: path
      required: true
      description: unique identifier for a reaction
      schema:
        type: string
        format: uuid
        minLength: 36
        maxLength: 36
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'



    XAppVersion:
      schema:
        type: string
        pattern: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
        minLength: 5
        maxLength: 16
      name: WASAText-version
      in: header
      required: true
      description: App human readable version ("semantic version" format)
      allowEmptyValue: false
    XAppBuild:
      schema:
        type: integer
        minimum: 0
      name: WASAText-Build
      in: header
      required: true
      description: App build number
      allowEmptyValue: false
    XAppLanguage:
      schema:
        type: string
        pattern: '^[a-z]{2}(?:[-_][A-Z]{2})?$'
        minLength: 2
        maxLength: 8
      name: WASAText-Language
      in: header
      required: true
      description: App language in ISO 639-1 format
      allowEmptyValue: false